"""

Revision ID: 461ffebcd6b4
Revises: 3c7c474a819a
Create Date: 2024-10-05 16:33:17.080044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461ffebcd6b4'
down_revision: Union[str, None] = '3c7c474a819a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('user', sa.UUID(), nullable=False))
    op.drop_constraint('resumes_user_id_fkey', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user'], ['id'])
    op.drop_column('resumes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key('resumes_user_id_fkey', 'resumes', 'users', ['user_id'], ['id'])
    op.drop_column('resumes', 'user')
    # ### end Alembic commands ###
