"""

Revision ID: 50ab32d45113
Revises: b90aa8e1baee
Create Date: 2024-10-05 17:24:28.687293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ab32d45113'
down_revision: Union[str, None] = 'b90aa8e1baee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_user_association', sa.Column('resume_id', sa.UUID(), nullable=False))
    op.drop_column('vacancy_user_association', 'ResumeId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_user_association', sa.Column('ResumeId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('vacancy_user_association', 'resume_id')
    # ### end Alembic commands ###
